# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ac1e2ed78ca077596978aa6a368043f4bc33a81f5d0136ad759a0967005dd28aa257b13bbf89647e341beda8a6580dd1625510894a8080ebf4fefdae2981e7

test:
  secret_key_base: 7fba909da7532a9aec055c78cb9c51acb3c8c89eea2b6bb2ac83885eefdc8dedc0ba18ee8471e5f256e11a104eddcee41cccdbd540e3c46bd3d75b5c893d7f95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
